baseURL = "https://example.org/"
languageCode = "en-us"
title = "Frank's Thoughts"
theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
